
# opencode
export PATH=/Users/jparsell/.opencode/bin:$PATH

# bun completions
[ -s "/Users/jparsell/.bun/_bun" ] && source "/Users/jparsell/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
